### PR TITLE
feat(browser): fetch and render favicons

### LINKED ISSUE #410: Favicon on browser tabs
## Describe the solution you'd like and the expected behavior
When a favicon is available for a page, it should be displayed in the tab.

## Is your feature request related to a problem? Please describe.
Favicons help to quickly scan for a tab that's already open.

## Possible implementation / References
Electron's webview has a [page-favicon-updated](https://electronjs.org/docs/api/webview-tag#event-page-favicon-updated) event, which can be used to get ahold of the favicon image URLs.  This can be used in conjunction with browserActions to track the favicon, and in turn load the image in the tab.

### PR DESCRIPTION
**Pull request by mhuggins**
## Description
This adds favicon fetching & rendering.  The webview provides an event that we can hook into for favicons updating, which we then use to fetch the image data and display it as a base64-encoded image.

## Motivation and Context
Favicons are helpful for quickly scanning tabs.

## How Has This Been Tested?
Loading sites w/ favicons in tabs.

## Screenshots (if appropriate)
favicons

## Types of changes
- [ ] Chore (tests, refactors, and fixes)
- [x] New feature (adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** guidelines and confirm that my code follows the code style of this project.
- [x] Tests for the changes have been added (for bug fixes/features)

#### Documentation
- [ ] Docs need to be added/updated (for bug fixes/features)

## Closing issues
Fixes #410.

### CODE REVIEW

**Comment by mhuggins** [comment]
I'll add some more tests for `fetchBestIcon` and the `Tab` component before we merge this.

**Comment by DalderupMaurice** [comment]
Sweet! Altough I had some occasions where it didn't load on the first time.
Besides that - LGTM - Ping when tests have been added

**Comment by mhuggins** [comment]
@DalderupMaurice I added the tests that I mentioned, so coverage should be good once the codecov report updates.

I'm a dummy and accidentally blew away your yarn.lock changes.  It's not clear to me what the changes were there, what was it?  Is it something we still need?

**Comment by DalderupMaurice** [comment]
removing the yarn.lock and re-adding it changed the registry urls from `npmjs` to `yarnpkg`, so no big deal I think.

**Pull request merged**
