### PR TITLE
Moved files into pods

### PR DESCRIPTION
**Pull request by mhuggins**
## Description
This flips the folder hierarchy on its head.  It introduces pods, each of which contains its own actions, components, hocs, shapes, values, etc.

In addition, it allows us to refer to pods absolutely.

```js
// before:
import Panel from '../../../../shared/components/Panel';

// after
import Panel from 'shared/components/Panel';
```

## Motivation and Context
Previously, each folder (e.g.: `components`) would have grown unbounded.  This organizes each set of files into a parent file that's related to its purpose.

## How Has This Been Tested?
* I ran `yarn lint` to ensure there were no file import path issues.
* I ran `yarn test` to ensure the tests pass.
* I ran `yarn start` to ensure the app starts & is fully navigable.

## Screenshots (if appropriate):
*Pods:*
src folder

*Pod Structure:*
pod structure

## Types of changes
- [x] Chore (tests, refactors, and fixes)
- [ ] New feature (adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] I have read the **CONTRIBUTING** document.

## Closing issues
N/A

### CODE REVIEW

**Comment by mhuggins** [comment]
Marking as work-in-progress.  There are a handful more components to move, which I'll do in the morning.

**Comment by mhuggins** [comment]
I'd also like to introduce [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) for each of the pods before merging.

**Comment by DalderupMaurice** [comment]
What's the status of this? :P 
I don't think reviewing 230+ files makes is the best way to verify the PR 😂

**Comment by mhuggins** [comment]
I think this is a good start that can probably be merged.  I wanted to get your PR in first then, since it's probably easier for me to rebase this against that change than it is for you to rebase your change against mine.

If you want to check it out, I'd recommend just pulling the branch and taking a look at the folder structure under `src` to see what you think.

**Pull request merged**
