### PR TITLE
feat(select): advanced select component design

### LINKED ISSUE #406: Select dropdown
## Describe the solution you'd like and the expected behavior
The current select input is using the native OS implementation.  This should be replaced with one that matches the designs, which includes advanced functionality (labels + icons, search, disabled/selectable).

## Is your feature request related to a problem? Please describe.
Updates the account screen to match designs.

## Possible implementation / References
N/A

### PR DESCRIPTION
**Pull request by mhuggins**
## Description
This updates the `Select` component to no longer behave as a native `select` element, but instead as a fully managed orchestration of components that can be rendered in a customized manner.  It introduces a new supporting `Dropdown` component, changes to the `Input` component for rendering icons/elements before & after, and search, keyboard support, and more for the `Select` component itself.

## Motivation and Context
The designs necessitate more advanced select/dropdown functionality.

## How Has This Been Tested?
* Smoke testing sending assets, changing networks, and changing currencies.
* Adding component tests.

## Screenshots (if appropriate)
select

## Types of changes
- [ ] Chore (tests, refactors, and fixes)
- [x] New feature (adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** guidelines and confirm that my code follows the code style of this project.
- [x] Tests for the changes have been added (for bug fixes/features)

#### Documentation
- [ ] Docs need to be added/updated (for bug fixes/features)

## Closing issues
Fixes #406.

### CODE REVIEW

**Comment by DalderupMaurice** [comment]
Clicking inside the input results in this error:
[](https://i.imgur.com/v9X6iOh.png)

**Comment by mhuggins** [comment]
@DalderupMaurice 

> Clicking inside the input results in this error

Which input did that happen on?

> It's maybe also a little confusing that you can't see what you had selected previously.

I could see that.  We might need a design iteration to address that though since it wasn't covered there.

**Comment by mhuggins** [comment]
> Which input did that happen on?

I'm seeing it on the "search" box now, I'm assuming that's the one you mean.

**Comment by mhuggins** [comment]
I rebased this branch, so you may need to delete your local copy and re-checkout to see the changes properly.

**Comment by DalderupMaurice** [comment]
It was on every input :P When you click it so it opens the dropdown and than click again in the field that where you can type

**Comment by mhuggins** [comment]
@DalderupMaurice I just checked the [.yarnrc documentation](https://yarnpkg.com/en/docs/yarnrc), but I don't see an option for pinning deps when installing.  Can you point me to where you've seen that?

**Comment by mhuggins** [comment]
I can't find the new GAS icon in the designs anymore.  I think it might have accidentally been removed.  I pinged the design team and will update as a follow-up PR.

**Comment by mhuggins** [comment]
> I assume `PureComponent` cannot be used with `shouldComponentUpdate`? (Never used the `anyPropsChanged` thing)

When you implement `PureComponent`, it's basically implementing shouldComponentUpdate for you with an `===` comparison of each old prop value to new prop value.  The `anyPropsChanged` function is something I implemented for checking just specific props instead of all props.

**Comment by mhuggins** [comment]
Just pushed a fix for the Add/Clear network functionality, nice catch!

**Comment by DalderupMaurice** [comment]
Uhh, I can't find it on the yarn website, but I use it for my own projects/at work.
Basically you have to add `save-prefix ""` in the `.yarnrc` file :P

**Comment by mhuggins** [comment]
@DalderupMaurice Made a few changes to address what you pointed out.  Tabbing past inputs should be fixed now, and the select maintains focus when a value is selected.  I also added a green focus ring around the select, similar to inputs.

**Comment by DalderupMaurice** [comment]
1 Last and final note 😄
Could/should we have a hover state and a pointer as a mouse? Similar to this (took this gif from ant design components page)


It would increase the natural feeling a ton :)

**Comment by mhuggins** [comment]
@DalderupMaurice I think those are all great suggestions, but we should coordinate with design for what that should look like.  I'll link them to your comment.

**Comment by mhuggins** [comment]
@DalderupMaurice Would you consider any of those issues blocking for merge?  Some of these changes in this PR are blocking the invocation modal changes, which is why I was hoping to get this in.  If they are blocking, that's fine -- just wanted to get a sense for how big these are.

**Comment by DalderupMaurice** [comment]
In that case I'd leave it open to merge 😄

**Pull request merged**
