### PR TITLE
feat(menu): browser zoom

### LINKED ISSUE #596: Zooming with Ctrl + Scroll & Context Menu
## Describe the solution you'd like and the expected behavior
Users should be able to zoom their pages using Ctrl + Scroll, or using the context menu.

### PR DESCRIPTION
**Pull request by mhuggins**
## Description
Implements zoom in, out, and actual size.

## Motivation and Context
Browser parity.

## How Has This Been Tested?
Using the menu options and keyboard shortcuts.

## Screenshots (if appropriate)
screen shot 2018-10-06 at 2 03 01 pm

## Types of changes
- [ ] Chore (tests, refactors, and fixes)
- [x] New feature (adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** guidelines and confirm that my code follows the code style of this project.
- [ ] Tests for the changes have been added (for bug fixes/features)

#### Documentation
- [ ] Docs need to be added/updated (for bug fixes/features)

## Closing issues
Fixes #596.

### CODE REVIEW

**Comment by DalderupMaurice** [comment]
Any scroll zoom capabilities possible? :P Just wondering

**Comment by DalderupMaurice** [comment]
client doesn't launch on windows

**Comment by mhuggins** [comment]
@DalderupMaurice Should be fixed in Windows now, thanks!

> Any scroll zoom capabilities possible?

We might be able to capture onmousewheel in our preload renderer doing [something like this](https://stackoverflow.com/a/7782164/107277).  I can take a look at that in a bit.

**Comment by mhuggins** [comment]
@DalderupMaurice mouse wheel zooming is now supported.  Works with Cmd+wheel on Mac, Ctrl+wheel on Windows.

**Comment by mhuggins** [comment]
@DalderupMaurice We'll need some design around that.  I think we should get this in as-is and revisit though since it's a significant improvement.

**Pull request merged**
