### PR TITLE
chore(button): update styles

### PR DESCRIPTION
**Pull request by mhuggins**
## Description
Updates button styles to match latest designs.

## Motivation and Context
See designs.

## How Has This Been Tested?
Hovering mouse, clicking button, tabbing to button, etc.

## Screenshots (if appropriate)
buttons

## Types of changes
- [x] Chore (tests, refactors, and fixes)
- [ ] New feature (adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** guidelines and confirm that my code follows the code style of this project.
- [ ] Tests for the changes have been added (for bug fixes/features)

#### Documentation
- [ ] Docs need to be added/updated (for bug fixes/features)

## Closing issues
N/A

### CODE REVIEW

**Comment by DalderupMaurice** [comment]
Is it me, or doesn't this look centered?

**Comment by DalderupMaurice** [comment]
I'm not sure if it fits the design 100%
What do you think? @fabric-8

**Comment by fabric-8** [comment]
@DalderupMaurice Looking good :) RE: Disabled style > How did that look before? :) Right now the idea was to use 50% opacity globally when an ui element is disabled which gives consistency + it's easy to handle, however happy to discuss that

**Comment by DalderupMaurice** [comment]
You can see the previous disabled state in the 2nd screenshot (Login button).
The implementation of this PR/the design is a gray button like the first screenshot (I updated my comment) @fabric-8

**Comment by fabric-8** [comment]
@DalderupMaurice Oops you are right, couldn't recall that one / not sure what happened here :) 
I fully agree with you & changed that in the styleguide as well, sorry about that & thx for the heads-up!

**Comment by mhuggins** [comment]
@fabric-8 I might need a hand figuring out what's going on with figma vs. my code change.  My style changes within `PrimaryButton.scss` appear to match up with the styles on figma, but when I hover/click on the buttons in the app, the styles don't match when I do it on the figma prototype.

**Comment by mhuggins** [comment]
Updated to match styles as best as possible.

**Pull request merged**
