### PR TITLE
Add Node.js LTS version in nvmrc file

### PR DESCRIPTION
**Pull request by robmoorman**

### CODE REVIEW

**Comment by DalderupMaurice** [comment]
I'd prefer defining the engine versions in the package.json instead of adding yet another file to the root folder

**Comment by robmoorman** [comment]
Ok, so we would like to provide a bandwith to node engine versions (8.11.x series all work). I'll do some testing with multiple version and provide an engine settings here.

**Comment by jeroenptrs** [comment]
I'm adding the node version to a branch, will merge this in that branch.
@robmoorman might want to set it to >= 8.11.1 and < 9.0.0, to support future LTS updates

**Comment by robmoorman** [comment]
We may want to ignore this pr @jeroenptrs in this case, as nvm only uses strict node version. It does support 'lts/*' versions, but this doesn't work well...

**Comment by jeroenptrs** [comment]
@robmoorman alright. I will close this PR then and will get to work on defining node versions in the package. I do want to stress that you should use the PR template next time by the way 😉

**Pull request closed without merging**
