### PR TITLE
feat(ledger): sign invocations

### LINKED ISSUE #560: Sign invocation transactions on Ledger
## Describe the solution you'd like and the expected behavior
When a Ledger user confirms an invocation, they should be prompted to sign the transaction on their Ledger device.

## Is your feature request related to a problem? Please describe.
Ledger users cannot successfully invoke transactions.

## Possible implementation / References
Use the signing function defined in the codebase already, and expose it on the auth redux store data.  If this function is present, then the user needs to sign.  Display a toast so the user knows they have to sign the transaction.

## Additional context
Ledger users who signed up for My nOS App & want to be involved in the ICO need to have this available.

### PR DESCRIPTION
**Pull request by mhuggins**
## Description
Adds Ledger support for invocation transactions.

**Note:** There is a bug with two toasts displaying instead of one that I haven't figured out yet.  I'll figure this out as a follow-up to this PR since it's pretty minor.

## Motivation and Context
Ledger users cannot currently complete invocation transactions successfully.

## How Has This Been Tested?
1. Log in with Ledger.
2. Open a create-react-app app that defines an invocation.
3. Click "Confirm" in the invocation prompt.
4. Sign or decline the transaction on the Ledger device.

## Screenshots (if appropriate)
ledger-invocation

## Types of changes
- [ ] Chore (tests, refactors, and fixes)
- [x] New feature (adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [x] I have read the **[CONTRIBUTING](./CONTRIBUTING.md)** guidelines and confirm that my code follows the code style of this project.
- [x] Tests for the changes have been added (for bug fixes/features)

#### Documentation
- [ ] Docs need to be added/updated (for bug fixes/features)

## Closing issues
Fixes #560.

### CODE REVIEW

**Comment by DalderupMaurice** [comment]
I cannot test this as I have no ledger (yet) :P @deanpress could you verify maybe? 
Code looks good

**Comment by mhuggins** [comment]
Just updated this branch to include all changes from `develop`.

**Comment by DalderupMaurice** [comment]
I wanted to test it this evening as I have my ledger setup :P I'll still verify it tonight and let you know

**Comment by mhuggins** [comment]
Whoops, sorry! Sounds good.

**Pull request merged**
